export const RELAYER_CLIENT = Symbol('RELAYER_CLIENT');
export const RELAYER_MODULE_OPTIONS = Symbol('RELAYER_MODULE_OPTIONS');
export const RELAYER_ENTITY_PREFIX = 'RELAYER_ENTITY_';
export const RELAYER_SERVICE_PREFIX = 'RELAYER_SERVICE_';
export const RELAYER_BASE_URL = Symbol('RELAYER_BASE_URL');
